# Objective of linear regression:

Find a linear *relationship* between an **independent variable *x*** and a **dependent variable *𝑦***.


$$
y = w * x + b
$$



- ## **w – Weight**:

```python
w = torch.tensor(2.0, requires_grad=True)
```

This is the **slope** of the line.

It determines how **much y changes each time x increases by 1**.

In the example:

If w = 2, this means that for every 1 increase in x, y increases by 2.

- ## **b – Bias (Intercept):**

```python
b = torch.tensor(-1.0, requires_grad=True)
```

**It is the initial value of y when x = 0**. It shifts the line up or down. 
In the example:b = -1 ⇒ The line intersects the y-axis at -1.
Example:If x = 0 ⇒ y = 2*0 + (-1) = -1 
Here too requires_grad=True because we want to optimize the bias if we were training a model.

| Variable | Meaning | Value | Effect |
| --------- | -------------------- | ------ | --------------------------------- |
| 'w' | Slope of the line | '2.0' | How much y "grows" with x |
| 'b' | Intercept | '-1.0' | Where the line on the y-axis "starts" |

In [4]:
import torch

## Base prediction: $y = w * x + b$ 
Let's manually **define w and b**

In [ ]:
w = torch.tensor(2.0, requires_grad=True)    
b = torch.tensor(-1.0, requires_grad=True)   

## Let's define the function $forward(x)$

In [7]:
def forward(x):
    return w * x + b

x = torch.tensor([[1.0]])
yhat = forward(x)
yhat

tensor([[1.]], grad_fn=<AddBackward0>)

### Prediction with more input

In [8]:
x = torch.tensor([[1.0], [2.0]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [9]:
from torch.nn import Linear 

torch.manual_seed(1)

lr = Linear(in_features=1, out_features=1, bias=True)

print(list(lr.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


| Concept | Description |
| :--- | :--- |
| `y = w * x + b` | The formula for **linear regression**, where `y` is the output, `x` is the input, `w` are the weights, and `b` is the bias. It represents the linear relationship between variables. |
| `forward()` | The function used for **prediction** in a machine learning model. It defines the flow of data through the neural network, calculating the model's output from the input. |
| `torch.nn.Linear` | A **PyTorch class** that implements a linear model. It's a pre-built module that performs the `y = w * x + b` operation. |
| `nn.Module` | The **base class** for all neural network modules and layers in PyTorch. It's the foundation for building custom and more complex models. |
| `state_dict()` | A **Python dictionary** that maps each model parameter (`w` and `b`) to its tensor. It's essential for saving, loading, and inspecting a model's weights. |